apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops
  namespace: argocd
spec:
  description: GitOps-managed applications

  sourceRepos:
    - http://host.docker.internal:8080/platform/cots-foss-tracker.git
    - https://grafana.github.io/helm-charts

  destinations:
    - namespace: gitops
      server: https://kubernetes.default.svc

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
