apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Argo CD platform and app-of-apps controller

  sourceRepos:
    - '*'

  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc

  namespaceResourceWhitelist:
    - group: argoproj.io
      kind: Application

  clusterResourceWhitelist: []

