apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cots-foss-root
  namespace: argocd
spec:
  project: gitops
  source:
    repoURL: http://host.docker.internal:8080/platform/cots-foss-tracker.git
    targetRevision: main
    path: argocd-apps/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

